            - name: Deploy to Github Environment
  # You may pin to the exact commit or the version.
  # uses: Tallyb/deployments@bc57855115ca415addbae3a4cff34c2847be47dc
  uses: Tallyb/deployments@0.5.0
  with:
    # GitHub token
    token: 
    # One of 'start' and 'finish'
    step: 
    # Set auto_inactive (see https://developer.github.com/v3/repos/deployments/#inactive-deployments)
    auto_inactive: # optional
    # URL to logs
    logs: # optional
    # Description to set in status
    desc: # optional
    # The git ref to use for the deploy, defaults to github.ref
    ref: # optional
    # Environment to create
    env: # optional
    # The url pointing to the created environment
    env_url: # optional
    # deployment status to set (for finish)
    status: # optional
    # the deployment id. Required for finish
    deployment_id: # optional
    # Specify transient environment. Defaults to true
    transient: # optional
          
